import type { Metadata } from "next";
import "@/app/globals.css";

export const metadata: Metadata = {
  title: "Connect With Me",
  description: "Generated by create next app",
};

export default function ConnectLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return <>{children}</>
}
