import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { NavBar } from "@/components/navigations";
import { ThemeInitializer } from "@/context/theme-context";
import CursorEffect from "@/components/ui/cursor-effect";
import ClientWrapper from "@/components/ui/ui-wrapper";

const inter = Inter({
  subsets: ["latin"],
  variable: "--font-inter",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`antialiased ${inter.variable}`}
      >
        <ThemeInitializer />
        <NavBar />
        <CursorEffect />
        <ClientWrapper>
          {children}
        </ClientWrapper>
      </body>
    </html>
  );
}
